"""initial schema

Revision ID: 4ced332841a1
Revises: 
Create Date: 2026-10-04 07:00:09.265295
"""
from alembic import op
import sqlalchemy as sa


revision = '4ced332841a1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canonical_products',
    sa.Column('canonical_id', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('substitution_group', sa.String(length=64), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('document', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('canonical_id')
    )
    with op.batch_alter_table('canonical_products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_canonical_products_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_canonical_products_substitution_group'), ['substitution_group'], unique=False)

    op.create_table('chains',
    sa.Column('chain_id', sa.String(length=64), nullable=False),
    sa.Column('document', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('chain_id')
    )
    op.create_table('households',
    sa.Column('household_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('api_key_hash', sa.String(length=64), nullable=False),
    sa.Column('postal_code', sa.String(length=10), nullable=False),
    sa.Column('document', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('household_id')
    )
    with op.batch_alter_table('households', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_households_api_key_hash'), ['api_key_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_households_postal_code'), ['postal_code'], unique=False)

    op.create_table('job_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_name', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_runs_job_name'), ['job_name'], unique=False)

    op.create_table('price_observations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('canonical_product_id', sa.String(length=64), nullable=False),
    sa.Column('retailer', sa.String(length=64), nullable=False),
    sa.Column('observed_on', sa.Date(), nullable=False),
    sa.Column('unit_price_minor_per_base', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('is_offer', sa.Boolean(), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('price_observations', schema=None) as batch_op:
        batch_op.create_index('ix_price_obs_product_retailer_time', ['canonical_product_id', 'retailer', 'observed_on'], unique=False)
        batch_op.create_index('ix_price_obs_product_time', ['canonical_product_id', 'observed_on'], unique=False)

    op.create_table('raw_offers',
    sa.Column('raw_id', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('document', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('raw_id')
    )
    with op.batch_alter_table('raw_offers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_raw_offers_captured_at'), ['captured_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_offers_source_id'), ['source_id'], unique=False)

    op.create_table('recipes',
    sa.Column('recipe_id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('main_protein', sa.String(length=32), nullable=True),
    sa.Column('document', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('recipe_id')
    )
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recipes_main_protein'), ['main_protein'], unique=False)

    op.create_table('review_queue',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('resolution', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_queue', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_queue_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_queue_status'), ['status'], unique=False)

    op.create_table('feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('household_id', sa.String(length=64), nullable=False),
    sa.Column('plan_id', sa.String(length=64), nullable=True),
    sa.Column('recipe_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], ['households.household_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feedback_household_id'), ['household_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_recipe_id'), ['recipe_id'], unique=False)

    op.create_table('offers',
    sa.Column('offer_id', sa.String(length=64), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('raw_id', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('retailer', sa.String(length=64), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('store_id', sa.String(length=64), nullable=True),
    sa.Column('region', sa.String(length=64), nullable=True),
    sa.Column('canonical_product_id', sa.String(length=64), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=False),
    sa.Column('validation_status', sa.String(length=20), nullable=False),
    sa.Column('price_confidence', sa.String(length=20), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(), nullable=False),
    sa.Column('document', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['raw_id'], ['raw_offers.raw_id'], ),
    sa.PrimaryKeyConstraint('offer_id'),
    sa.UniqueConstraint('fingerprint')
    )
    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_offers_canonical_product_id'), ['canonical_product_id'], unique=False)
        batch_op.create_index('ix_offers_retailer_validity', ['retailer', 'valid_from', 'valid_to'], unique=False)
        batch_op.create_index(batch_op.f('ix_offers_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_offers_store_id'), ['store_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_offers_validation_status'), ['validation_status'], unique=False)

    op.create_table('pantry_lots',
    sa.Column('lot_id', sa.String(length=64), nullable=False),
    sa.Column('household_id', sa.String(length=64), nullable=False),
    sa.Column('canonical_product_id', sa.String(length=64), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('document', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.household_id'], ),
    sa.PrimaryKeyConstraint('lot_id')
    )
    with op.batch_alter_table('pantry_lots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pantry_lots_canonical_product_id'), ['canonical_product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pantry_lots_household_id'), ['household_id'], unique=False)

    op.create_table('pantry_versions',
    sa.Column('household_id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.household_id'], ),
    sa.PrimaryKeyConstraint('household_id')
    )
    op.create_table('plans',
    sa.Column('plan_id', sa.String(length=64), nullable=False),
    sa.Column('household_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('optimizer_version', sa.String(length=32), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('document', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.household_id'], ),
    sa.PrimaryKeyConstraint('plan_id'),
    sa.UniqueConstraint('household_id', 'idempotency_key', name='uq_plan_idem')
    )
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plans_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_plans_household_id'), ['household_id'], unique=False)

    op.create_table('product_aliases',
    sa.Column('alias', sa.String(length=200), nullable=False),
    sa.Column('canonical_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['canonical_id'], ['canonical_products.canonical_id'], ),
    sa.PrimaryKeyConstraint('alias')
    )
    with op.batch_alter_table('product_aliases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_aliases_canonical_id'), ['canonical_id'], unique=False)

    op.create_table('stores',
    sa.Column('store_id', sa.String(length=64), nullable=False),
    sa.Column('chain_id', sa.String(length=64), nullable=False),
    sa.Column('postal_code', sa.String(length=10), nullable=False),
    sa.Column('region', sa.String(length=64), nullable=True),
    sa.Column('document', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['chain_id'], ['chains.chain_id'], ),
    sa.PrimaryKeyConstraint('store_id')
    )
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stores_chain_id'), ['chain_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stores_postal_code'), ['postal_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_stores_region'), ['region'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stores_region'))
        batch_op.drop_index(batch_op.f('ix_stores_postal_code'))
        batch_op.drop_index(batch_op.f('ix_stores_chain_id'))

    op.drop_table('stores')
    with op.batch_alter_table('product_aliases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_aliases_canonical_id'))

    op.drop_table('product_aliases')
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plans_household_id'))
        batch_op.drop_index(batch_op.f('ix_plans_created_at'))

    op.drop_table('plans')
    op.drop_table('pantry_versions')
    with op.batch_alter_table('pantry_lots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pantry_lots_household_id'))
        batch_op.drop_index(batch_op.f('ix_pantry_lots_canonical_product_id'))

    op.drop_table('pantry_lots')
    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_offers_validation_status'))
        batch_op.drop_index(batch_op.f('ix_offers_store_id'))
        batch_op.drop_index(batch_op.f('ix_offers_source_id'))
        batch_op.drop_index('ix_offers_retailer_validity')
        batch_op.drop_index(batch_op.f('ix_offers_canonical_product_id'))

    op.drop_table('offers')
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedback_recipe_id'))
        batch_op.drop_index(batch_op.f('ix_feedback_household_id'))

    op.drop_table('feedback')
    with op.batch_alter_table('review_queue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_queue_status'))
        batch_op.drop_index(batch_op.f('ix_review_queue_kind'))

    op.drop_table('review_queue')
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipes_main_protein'))

    op.drop_table('recipes')
    with op.batch_alter_table('raw_offers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_raw_offers_source_id'))
        batch_op.drop_index(batch_op.f('ix_raw_offers_captured_at'))

    op.drop_table('raw_offers')
    with op.batch_alter_table('price_observations', schema=None) as batch_op:
        batch_op.drop_index('ix_price_obs_product_time')
        batch_op.drop_index('ix_price_obs_product_retailer_time')

    op.drop_table('price_observations')
    with op.batch_alter_table('job_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_runs_job_name'))

    op.drop_table('job_runs')
    with op.batch_alter_table('households', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_households_postal_code'))
        batch_op.drop_index(batch_op.f('ix_households_api_key_hash'))

    op.drop_table('households')
    op.drop_table('chains')
    with op.batch_alter_table('canonical_products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_canonical_products_substitution_group'))
        batch_op.drop_index(batch_op.f('ix_canonical_products_category'))

    op.drop_table('canonical_products')
    # ### end Alembic commands ###
